from mayacmds_a import *
from mayacmds_b import *
from mayacmds_c import *
from mayacmds_d import *
from mayacmds_e import *
from mayacmds_f import *
from mayacmds_g import *
from mayacmds_h import *
from mayacmds_i import *
from mayacmds_j import *
from mayacmds_k import *
from mayacmds_l import *
from mayacmds_m import *
from mayacmds_n import *
from mayacmds_o import *
from mayacmds_p import *
from mayacmds_q import *
from mayacmds_r import *
from mayacmds_s import *
from mayacmds_t import *
from mayacmds_u import *
from mayacmds_v import *
from mayacmds_w import *
from mayacmds_x import *
